### ISSUE TITLE
Can't find anything in grub configuration file

### ISSUE THREAD

**Issue by wazoox** [error10/kexec-reboot#3]
Could you post an example of your grub.cfg file? Mine are always heavily customized and the regex line 113 fails miserably to match anything, and it looks like it search for a very restricted but elaborate predefined formatting which probably only matches your own distribution....

**Comment by error10** [comment]
How do you end up with a "heavily customized" auto-generated file? What distribution are you using?

**Comment by wazoox** [comment]
Debian. You can perfectly change the scripts that generate the grub.cfg,
and I do :)

2015-04-02 0:08 GMT+02:00 error10 notifications@github.com:
